### ISSUE TITLE
move Kalite functionality out of lessons package into kalite package

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ooskapenaar/awarenet#383]
```
Kalite is at the moment integrated into the lessons package. Strix thinks and I 
agree that this functionality is better placed into its own package.

```

Original issue reported on code.google.com by `appiapp...@gmail.com` on 3 Apr 2014 at 7:30

**Comment by awarenetdev** [comment]
Closing, KALite currently works as expected - while it would be nice to reorganize, will leave current arrangement as stable.
