### ISSUE TITLE
Quality Assurance Task 1 - Check/Synchronize code in Packages and SVN Codebase

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ooskapenaar/awarenet#385]
```
I will go through all packages and eliminate any differences between latest 
code checked in into SVN and the packages managed by the Kapenta Package 
Manager. 

This task will ensure that the latest code available in the SVN code base is 
actually the code that is installable in the Kapenta Packages.
```

Original issue reported on code.google.com by `appiapp...@gmail.com` on 2 May 2014 at 11:00

**Comment by AMWertlen** [comment]
Hi @awarenetdev , let us know if Michael has finished this task, if you have a spare minute. Thank you.

**Comment by AMWertlen** [comment]
Hi @awarenetdev, now that we are on github, this task is hopefully easier?  Are our codebases synchronised?  Can we make Github the master codebase, please? 
Thank you.

**Comment by awarenetdev** [comment]
Hi Anna,

> Are our codebases synchronised? 

Yes,

> Can we make Github the master codebase, please? 

Already done.  Github is the development codebase.  For deployment we use the kapenta package system, which is fed from a fork of this git repo.

**Comment by AMWertlen** [comment]
Great. :+1: So, we can close this issue...
Thank you.
