### ISSUE TITLE
display direction of discussion thread

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ooskapenaar/awarenet#390]
```
Following the logic of placing the "reply to a discussion" field on top of the 
discussion, I suggest to display the newest comment on top as well. 

Can be discussed.
```

Original issue reported on code.google.com by `a...@villagescribe.org` on 2 Jul 2014 at 11:21

**Comment by AMWertlen** [comment]
Just following up on the last two comments...

**Comment by mrlordsegi** [comment]
It looks like that the problem is solved. The newest comment, the textbox as well as the "reply to this discussion" are at the top of the page!
