### ISSUE TITLE
Teacher Wiki

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ooskapenaar/awarenet#394]
```
For the teacher training course (Feb-Mar), we would need a wiki, in which 
teachers can share information etc.

Please, can we have a Wiki:
* empty
* rights: only teachers and admins
* in menu perhaps between forums and help

Ron will have a look into it, but will need some help.


```

Original issue reported on code.google.com by `a...@villagescribe.org` on 13 Jan 2015 at 8:52

**Comment by AMWertlen** [comment]
@awarenetdev and @mrlordsegi 

New idea of @ooskapenaar, @McKimi and @awarenetdev is to integrate a Moodle to be used as a teacher wiki/CMS. Research underway.

**Comment by AMWertlen** [comment]
No capacity to develop that now.
