### ISSUE TITLE
chat doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ooskapenaar/awarenet#395]
```
What steps will reproduce the problem?
1. visit "http://awarenet.eu/chat/"
2. click on "Global Chat"
3.

What is the expected output? What do you see instead?
I see this error message (see attached pic). It happend to me while using 
Firefox 31.0 (in VB), IE 11 and Opera 26. Its always the same error.

Please use labels and text to provide additional information.


```

Original issue reported on code.google.com by `MrLordS...@gmail.com` on 16 Jan 2015 at 8:15

Attachments:
* [error.png](https://storage.googleapis.com/google-code-attachments/awarenet/issue-395/comment-0/error.png)

**Comment by mrlordsegi** [comment]
We tested it while you were visiting. It worked for me neither with IE11 nor with Opera29. 
Firefox 36 worked 2 out of 3 times in the lab.

**Comment by AMWertlen** [comment]
Hi Lukas, can you check if the learners in the JYH lab can chat to each other during the next sessions, please?

**Comment by mrlordsegi** [comment]
Hey I'll do that! Since we're doing sports at the moment it may take a week.

2015-05-04 12:24 GMT+02:00 AMWertlen <notifications@github.com>:

**Comment by AMWertlen** [comment]
Chat between volunteers and me on awarenet.eu works.

**Comment by mrlordsegi** [comment]
Works here as well! I close it.
