### ISSUE TITLE
Copy paste in text box

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ooskapenaar/awarenet#397]
```
The learners sometimes work on word (no inet, troubles with lap set up etc). 
When I tried to copy\paste the written texts (different fonts, colours) in the 
blog section, awarenet crashed or the texts were gone and the blogs empty. 
Probably because awarenet doesn't know the formattings?!
I think this effects esp. the teachers who might put (using copy-paste) a lot 
of texts of their learners or of study material on awarenet.




```

Original issue reported on code.google.com by `MrLordS...@gmail.com` on 16 Jan 2015 at 9:34

**Comment by ooskapenaar** [comment]
Comment #4 on issue 397 by anna@villagescribe.org: Copy paste in text box
https://code.google.com/p/awarenet/issues/detail?id=397

Mcvay will do some research on a free text editor. Please, follow up with him, Lukas.

They should be installed in the hub and Ntaba Maria.

Blogs must be written in the text editor etc.

**Comment by AMWertlen** [comment]
Hi @mrlordsegi, ist there a text editor at the hub?

**Comment by mrlordsegi** [comment]
Yes,there is. Called "Text Editor" :)

**Comment by AMWertlen** [comment]
Does it work for you? Can you live like that?

**Comment by mrlordsegi** [comment]
Yes I can :) 
There is one at Ntaba as well. So I'll close this issue.
