### ISSUE TITLE
Word counter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ooskapenaar/awarenet#399]
```
we often ask to learners to write a text consisting of at least XXX words. 
Therefore a word counter would be nice to have implemented in every text-box 
(blog, forum etc.)
```

Original issue reported on code.google.com by `MrLordS...@gmail.com` on 16 Jan 2015 at 9:39

**Comment by awarenetdev** [comment]
Have added this, is live on awarenet.eu

**Comment by mrlordsegi** [comment]
Maybe its me but I'm not able to find the word count button on awarenet.eu. Neither in the blog section nor in the forum section.
![no button](https://cloud.githubusercontent.com/assets/12064953/7856088/b2a90d3e-0526-11e5-9b64-f464d24cee80.png)

**Comment by awarenetdev** [comment]
Hi, you might need to reload the page, icon should appear to the right of the HTML button.

![awarenet word count](https://cloud.githubusercontent.com/assets/8433213/7856275/31398088-0528-11e5-929c-68144457b5db.jpg)

**Comment by mrlordsegi** [comment]
Ah, thank you so much. It looks nice! Cleaning the history worked.
