### ISSUE TITLE
User search at the right top corner

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ooskapenaar/awarenet#402]
```
When my learners are searching for friends on awarenet they always use the 
"global" search funktion at the right top of the page. Since this one is not 
really working for people could we maybe put there the "user search" instead?! 
I never saw someone searching for something else than people...
Therefore I think it is an easy and well appreciated enhancement!


```

Original issue reported on code.google.com by `MrLordS...@gmail.com` on 10 Mar 2015 at 10:29

**Comment by AMWertlen** [comment]
I am unable to say how much work this is. Strix, do you think this can be done easily?

**Comment by awarenetdev** [comment]
Have implemented and applied to awarenet.eu.

**Comment by mrlordsegi** [comment]
I'm affraid I can't see any difference on awarenet.eu. The search for "Anna Wertlen" was successfully using the search function in the "people" section but didn't work using the "global search" in the right top corner. If I click on a tag "Anna-Wertlen" (as a "work-around" using the global search to get to the profile) I get directed to "Oops, something went wrong".

![user search](https://cloud.githubusercontent.com/assets/12064953/7856279/36756580-0528-11e5-92a6-377906bba217.png)

**Comment by awarenetdev** [comment]
Your screenshot shows it doing a tag search, not a user search, you need to press F5 to reload the page and fetch new copies of scripts which have been changed, or clear your browser history.

![awarenet user search](https://cloud.githubusercontent.com/assets/8433213/7856525/161eb67c-052a-11e5-9dd3-bbf3bbda1d9f.jpg)

**Comment by mrlordsegi** [comment]
Ah, thank you so much. It looks nice! Cleaning the history worked.
