### ISSUE TITLE
default page for lessons

### ISSUE THREAD

**Issue by AMWertlen** [ooskapenaar/awarenet#409]
Hi Strix.
Kjetil would like to focus on videos and lessons in awarenet. At the moment, the default page when clicking on http://awarenet.eu/lessons/ is the KaLite, which gives an error message, so users too easily turn away and won't find the other video lessons. Can the default instead be http://awarenet.eu/lessons/list/videosxh?
Thank you, Anna

**Comment by awarenetdev** [comment]
default changed on awarenet.eu

**Comment by kjetiltorp** [comment]
Fantastic Strix! You are a genius! Cannot thank you enough, this issue was bringing me nightmares but now I can finally close it and regain my sorely missed beauty sleep...
